### ISSUE TITLE
move `main!` macro to its own crate

### ISSUE THREAD

**Issue by vitiral** [killercup/quicli#17]
I mainly want this so I can steal it in and use it in stdcli!

https://github.com/vitiral/stdcli/issues/2

**Comment by killercup** [comment]
Sure, I'm okay with that. It's just that there is at least one huge problem we need to solve:

*What should we call this new crate?*

(Some other, minor things: Do you want to have the cli parsing and logging stuff as well? If not, it might be easier to just copy the file actually.)

**Comment by killercup** [comment]
Hm, not sure if a crate like this pulls its own weight. I means, ?-in-main [works](https://play.rust-lang.org/?gist=25d12b1cf4ebeda0eadb2e5eb3a86cd7&version=nightly) in nightly already, incl. nice errors.

**Comment by vitiral** [comment]
ya, just waiting for nightly is probably good enough for now -- considering it is definitely something on the "hotpath" since it improves docs so much.

Closing this, although I really like the crate name `mainline`

**Comment by vitiral** [comment]
Also, I'm probably just going to inherit this crate as a dependency directly instead, as said in #19
