### ISSUE TITLE
rexport std_prelude in prelude

### ISSUE THREAD

**Issue by vitiral** [killercup/quicli#18]
https://github.com/vitiral/std_prelude

I personally feel like this makes writing quick things in rust much more ergonomic.

I'm openeing a separate issue for a discussion on the overal design goals of this lib

**Comment by killercup** [comment]
Wow, just read through your [docs](https://docs.rs/std_prelude/0.2.9/std_prelude/). This is impressive!

I want to add our re-exports a bit more deliberate, though. I'll write a bit more in #19.

**Comment by killercup** [comment]
tl;dr from #19: I'm good with re-exporting some crates but would rather add some abstraction around common use cases.

**Comment by vitiral** [comment]
closing per #19
