### ISSUE TITLE
#[derive(Fail) fails

### ISSUE THREAD

**Issue by spease** [killercup/quicli#37]
I receive an error about missing crate "failure" - looks like it's probably the same situation as serde. Perhaps failure can be reexported inside a namespace with the same name to preserve the macro functionality? Or it should be added to serde and structopt in the list of things you should add to Cargo.toml to use everything.

**Comment by killercup** [comment]
Thanks for reporting this. I kinda expected this to happen; this `extern
crate` in derive-generated code is a well-known hack to get around some
limitations.

I think for know, you'll need to add failure as a dependency, like serde
and structopt.

Or, don't create your own error type and use strings ;)

spease <notifications@github.com> schrieb am Do. 1. Feb. 2018 um 00:39:
