### ISSUE TITLE
Main return type has not enough constraints?

### ISSUE THREAD

**Issue by killercup** [killercup/quicli#42]
See #41's CI [logs](https://travis-ci.org/killercup/quicli/jobs/337007264#L582):

> Huh, some problems with compiling waltz? Ohhh, or maybe the quicli override in .cargo/context caught that? Which is super weird, and may point to the fact that #32 was not completely done? I'll need to investigate this.

**Comment by yoshuawuyts** [comment]
I've found the configure crate to be really elegant; it might compliment the failure crate nicely here. https://docs.rs/configure/0.1.1/configure/

**Comment by killercup** [comment]
I rolled back #32 in 0.1.4 (i think), so this can be closed for now
