### ISSUE TITLE
fs::write_to_file doc test fails on Windows

### ISSUE THREAD

**Issue by CAD97** [killercup/quicli#49]
`/tmp/asdasidz81zasda` isn't a valid path on Windows.

Use [`std::env::temp_dir`](https://doc.rust-lang.org/std/env/fn.temp_dir.html) for a cross-platform way to get the temp file directory.

**Comment by killercup** [comment]
This is the offending code:

https://github.com/killercup/quicli/blob/a3b674ccaf30f1fd2896aead8b1af5648c4a8981/src/fs.rs#L47-L60

Can we just change the test to something like `write_to_file("/tmp/asdasidz81zasda", "foobar")?;`?

**Comment by CAD97** [comment]
For the most part I believe examples that utilize File IO are usually not run as tests. However, doing so _is_ useful, so I'm not sure exactly what should be done.

I'd personally probably do something along the lines of

- Don't change the contents of the doc example that are shown
- Mark the doc example as no_run
- Make a `#[test]` test that creates and cleans up a temp file in the proper system-agnostic manner

**Comment by CAD97** [comment]
Also, @killercup, I don't know if that was a typo, but you seem to have proposed to change the test to the exact same as what's currently present.

**Comment by killercup** [comment]
Oops, sorry that was meant to be a relative path! I agree with your main
suggestion, though: we should use tempdir here.

(I.e., add it as a dev-dependency and extend the doc test with a few more
hidden lines.)

Christopher Durham <notifications@github.com> schrieb am Sa. 17. Feb. 2018
um 05:49:

**Comment by killercup** [comment]
Fixed by #86
