### ISSUE TITLE
Update Rayon dependency to 1.0

### ISSUE THREAD

**Issue by killercup** [killercup/quicli#58]
- [ ] Bump rayon's version number
- [ ] Figure out if this is a breaking change to quicli
  - Is there code out there that will no longer compile?

**Comment by CAD97** [comment]
> Breaking changes
> 
> - Rayon now requires rustc 1.13 or greater.
> - `IndexedParallelIterator::len` and `ParallelIterator::opt_len` now operate on `&self` instead of `&mut self`.
> - `IndexedParallelIterator::collect_into` is now `collect_into_vec`.
> - `IndexedParallelIterator::unzip_into` is now `unzip_into_vecs`.
> - Rayon no longer exports the deprecated `Configuration` and `initialize` from rayon-core.

> rustc 1.13 or greater

If `quicli` already requires `rustc` >= 1.13, we're good here. That doesn't seem to be explicitly documented yet.

> IndexedParallelIterator::{len, collect_into[_vec], unzip_into[_vec] and ParallelIterator::opt_len

Both traits are in `rayon::prelude` and are thus publicly re-exported from `quicli`, making a breaking change there a breaking change to `quicli`.

> `Configuration` and `initialize`

Were not exported in `rayon::prelude`, so doesn't effect the stability of `quicli`.

**Comment by killercup** [comment]
quicli re-exports proc-macros, so it requires 1.15+ (I've only tested it with the latest stable, though.)

Alright, it's a major version bump, then. I'm totally fine with that, we still have some version numbers left to use :)

**Comment by ariasuni** [comment]
As #73 was merged, you should probably close this issue, right?

**Comment by killercup** [comment]
Yep! Thanks :)
