### ISSUE TITLE
Verbosity flag does not work when package name != crate name

### ISSUE THREAD

**Issue by CAD97** [killercup/quicli#60]
This was very weird to diagnose, since I couldn't figure out why it worked in `playground` but not in my real project (that has hyphens in its name) until I guessed that this was the problem.

When setting `package.name = "crate-name"`, the actual crate name will be `crate_name`. The log filter should be registered for `crate_name` but is currently registered for `crate-name`. (It may be a failing of `env_logger` to not accept either, but we can do better.)

**Comment by killercup** [comment]
We are just using the environment variable Cargo gives us here.

Is there something we can do differently here without a build script or proc macro?

**Comment by CAD97** [comment]
I'm now using `env!("CARGO_PKG_NAME").replace("-","_")` (mod typing that on a phone without checking syntax) which works properly
