### ISSUE TITLE
export clap macros

### ISSUE THREAD

**Issue by vitiral** [killercup/quicli#71]
clap exports very useful macros such as [crate_version](https://docs.rs/clap/2.31.1/clap/macro.crate_version.html) etc. These should be exported if possible.

Also, I think it is okay to export the other clap types, since sometimes you want to access `App` directly even if you are using `structopt`.

**Comment by killercup** [comment]
What's the use case for crate_version? Structopt uses it internally already.

**Comment by vitiral** [comment]
oh that's right. I forgot that most of this is handled for you by structopt!

The use case was brought up in the CLI-wg chat (that they didn't know of a way to find the info) but it's already provided so _shrug_.
