### ISSUE TITLE
Readme example doesn't compile

### ISSUE THREAD

**Issue by BackwardSpy** [killercup/quicli#81]
Hi, I tried to compile the [Readme example](https://github.com/killercup/quicli/blob/master/examples/Readme/src/main.rs) and I got two errors saying that `StructOpt` and `Verbosity` are not found in scope. Should these be added to the prelude?

**Comment by killercup** [comment]
Oh! That is referring to quicli's master branch, not a released version. That's quite unfortunate. I had planned to release a new version last week but that didn't happen yet. I'll try to get around to it this weekend.

In the meantime, you can look at this https://github.com/killercup/quicli/tree/v0.2.0 version of the repository.

Sorry for the confusion!

**Comment by BackwardSpy** [comment]
Ah, that makes a lot of sense! Thanks for clearing it up.
